-- Adminer 4.7.0 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

CREATE DATABASE `dip_tour` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `dip_tour`;

INSERT INTO `visa_details` (`id`, `nationality`, `destination`, `country_of_resident`, `purpose_of_travel`, `show_application_info`, `show_visa_checklist`, `show_visa_application_center`, `show_embassy`, `visa_fee`, `application_link`, `processing_time`, `application_form`, `bank_statement`, `proof_of_accommodation`, `passport_and_validity`, `letter_of_introduction`, `letter_of_invitation`, `passport_photograph`, `other_documents`, `visa_application_center`, `embassy`) VALUES
(1,	'India',	'UAE',	'India',	'Work',	'Yes',	'Yes',	'Yes',	'Yes',	'20000',	'www.google.cpm',	'6000',	'Visa Application Form',	'6 months',	'Hotel Reservation or address of relative sending invitation or accomodation provided by company',	'minimum 6 month validity',	'Original needed',	'if applicable',	'4X5 cms photos in white background',	'optional',	'&#x3C;p class=&#x22;lead m-t-0&#x22;&#x3E;Consulate-General of the Republic of Nauru Queensland &#x3C;/p&#x3E;\r\n                                                &#x3C;address&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Telephone&#x22;&#x3E;T:&#x3C;/abbr&#x3E; (07) 3220 3040 &#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Email&#x22;&#x3E;E:&#x3C;/abbr&#x3E; nauru.consulate@brisbane.gov.nr&#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Address&#x22;&#x3E;A:&#x3C;/abbr&#x3E; Level 3, 99 Creek Street Qld 4000&#x3C;br&#x3E;\r\n                                                    Brisbane &#x3C;br&#x3E;Queensland  &#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Payment Detail&#x22;&#x3E;P:&#x3C;/abbr&#x3E; &#x3C;br&#x3E;\r\n                                                &#x3C;/address&#x3E;\r\n                                                &#x3C;blockquote&#x3E;\r\n                                                    Hours of Business: Monday - Friday 9.00&#x3C;br&#x3E;\r\n                                                    am - 5.00 p.m.\r\n                                                &#x3C;/blockquote&#x3E;',	'&#x3C;p class=&#x22;lead m-t-0&#x22;&#x3E;Zimbabwean Embassy Abuja&#x3C;/p&#x3E;\r\n                                            &#x3C;address&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Telephone&#x22;&#x3E;T:&#x3C;/abbr&#x3E; (+234) 9-461 1322&#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Email&#x22;&#x3E;E:&#x3C;/abbr&#x3E; zimabuja@infoweb.abs.net&#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Website&#x22;&#x3E;W:&#x3C;/abbr&#x3E; &#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Address&#x22;&#x3E;A:&#x3C;/abbr&#x3E; 60, Parakou Crescent, Off Aminu Kano Crescent&#x3C;br&#x3E;\r\n                                                Wuse II&#x3C;br&#x3E;Abuja&#x3C;br&#x3E;\r\n                                            &#x3C;/address&#x3E;\r\n                                            &#x3C;blockquote&#x3E;\r\n                                                60, Parakou Crescent, Off Aminu Kano&#x3C;br&#x3E;\r\n                                                Crescent\r\n                                            &#x3C;/blockquote&#x3E;'),
(2,	'Bangladesh',	'UAE',	'Bangladesh',	'Work',	'Yes',	'Yes',	'Yes',	'Yes',	'20000',	'www.google.cpm',	'6000',	'Visa Application Form',	'6 months',	'Hotel Reservation or address of relative sending invitation or accomodation provided by company',	'minimum 6 month validity',	'Original needed',	'if applicable',	'4X5 cms photos in white background',	'optional',	'&#x3C;p class=&#x22;lead m-t-0&#x22;&#x3E;Consulate-General of the Republic of Nauru Queensland &#x3C;/p&#x3E;\r\n                                                &#x3C;address&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Telephone&#x22;&#x3E;T:&#x3C;/abbr&#x3E; (07) 3220 3040 &#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Email&#x22;&#x3E;E:&#x3C;/abbr&#x3E; nauru.consulate@brisbane.gov.nr&#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Address&#x22;&#x3E;A:&#x3C;/abbr&#x3E; Level 3, 99 Creek Street Qld 4000&#x3C;br&#x3E;\r\n                                                    Brisbane &#x3C;br&#x3E;Queensland  &#x3C;br&#x3E;\r\n                                                    &#x3C;abbr title=&#x22;Payment Detail&#x22;&#x3E;P:&#x3C;/abbr&#x3E; &#x3C;br&#x3E;\r\n                                                &#x3C;/address&#x3E;\r\n                                                &#x3C;blockquote&#x3E;\r\n                                                    Hours of Business: Monday - Friday 9.00&#x3C;br&#x3E;\r\n                                                    am - 5.00 p.m.\r\n                                                &#x3C;/blockquote&#x3E;',	'&#x3C;p class=&#x22;lead m-t-0&#x22;&#x3E;Zimbabwean Embassy Abuja&#x3C;/p&#x3E;\r\n                                            &#x3C;address&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Telephone&#x22;&#x3E;T:&#x3C;/abbr&#x3E; (+234) 9-461 1322&#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Email&#x22;&#x3E;E:&#x3C;/abbr&#x3E; zimabuja@infoweb.abs.net&#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Website&#x22;&#x3E;W:&#x3C;/abbr&#x3E; &#x3C;br&#x3E;\r\n                                                &#x3C;abbr title=&#x22;Address&#x22;&#x3E;A:&#x3C;/abbr&#x3E; 60, Parakou Crescent, Off Aminu Kano Crescent&#x3C;br&#x3E;\r\n                                                Wuse II&#x3C;br&#x3E;Abuja&#x3C;br&#x3E;\r\n                                            &#x3C;/address&#x3E;\r\n                                            &#x3C;blockquote&#x3E;\r\n                                                60, Parakou Crescent, Off Aminu Kano&#x3C;br&#x3E;\r\n                                                Crescent\r\n                                            &#x3C;/blockquote&#x3E;');

-- 2019-11-30 17:51:59
